import { z } from 'zod'

import type { UtenteEditFormValues } from '../types/utente-edit-form-types'

export const utenteEditSchema = z
  .object({
    nome: z.string().min(1, 'Nome é obrigatório'),
    numeroContribuinte: z.string().min(1, 'NIF é obrigatório'),
    numeroUtente: z.string().optional(),
    observacoes: z.string().min(1, 'Observações é obrigatório'),
    status: z.coerce.number().int().min(0).max(3),
    aviso: z.string().optional(),
    desistencia: z.boolean().optional(),
    tipoConsulta: z.coerce.number().int().min(0).max(3).optional(),
    // Dados pessoais
    dataNascimento: z.string().optional(),
    dataEmissaoCartaoIdentificacao: z.string().optional(),
    dataValidadeCartaoIdentificacao: z.string().optional(),
    sexoId: z.string().nullable().optional(),
    estadoCivilId: z.string().nullable().optional(),
    habilitacaoId: z.string().nullable().optional(),
    grupoSanguineoId: z.string().nullable().optional(),
    cronico: z.boolean().optional(),
    numeroCartaoIdentificacao: z.string().optional(),
    nomeMae: z.string().optional(),
    nomePai: z.string().optional(),
    naturalidade: z.string().optional(),
    nacionalidade: z.string().optional(),
    profissaoId: z.string().nullable().optional(),
    arquivo: z.string().optional(),
    ccValidado: z.union([z.coerce.number(), z.null()]).optional(),
    ccDataValidacao: z.string().optional(),
    // Contactos – Morada (obrigatório conforme backend)
    paisId: z.string().min(1, 'País é obrigatório'),
    distritoId: z.string().min(1, 'Distrito é obrigatório'),
    concelhoId: z.string().min(1, 'Concelho é obrigatório'),
    freguesiaId: z.string().min(1, 'Freguesia é obrigatória'),
    codigoPostalId: z.string().min(1, 'Código Postal é obrigatório'),
    rua: z.string().optional(),
    ruaId: z.string().optional(),
    numeroPorta: z.string().min(1, 'N.º Porta é obrigatório'),
    andarRua: z.string().min(1, 'Andar é obrigatório'),
    morada: z.string().optional(),
    indicativoTelefone: z.string().optional(),
    telefone: z.string().optional(),
    telemovel: z.string().optional(),
    // Informação SNS
    numeroSegurancaSocial: z.string().optional(),
    tipoTaxaModeradora: z.union([z.coerce.number(), z.null()]).optional(),
    migrante: z.boolean().optional(),
    nDocMigrante: z.string().optional(),
    condicaoSns: z.union([z.coerce.number(), z.null()]).optional(),
    entidadeFinanceiraResponsavelId: z.string().nullable().optional(),
    numeroBeneficiarioEfr: z.string().optional(),
    dataValidadeEfr: z.string().optional(),
    migranteTipoCartao: z.string().optional(),
    // Outras Informações
    provenienciaUtenteId: z.string().nullable().optional(),
    // Subsistema de Saúde
    organismoId: z.string().nullable().optional(),
    seguradoraId: z.string().nullable().optional(),
    // Informação SNS
    centroSaudeId: z.string().nullable().optional(),
    medicoExternoId: z.string().nullable().optional(),
    medicoId: z.string().nullable().optional(),
    subsistemaLinhas: z
      .array(
        z.object({
          organismoId: z.string().nullable().optional(),
          designacao: z.string().optional(),
          numeroBeneficiario: z.string().optional(),
          sigla: z.string().optional(),
          nomeBeneficiario: z.string().optional(),
          dataCartao: z.string().optional(),
          numeroApolice: z.string().optional(),
          empresaId: z.string().nullable().optional(),
          empresaNome: z.string().optional(),
        }),
      )
      .optional(),
    empresaId: z.string().nullable().optional(),
    // Status (UI)
    statusSelecionado: z.boolean().optional(),
  })
  .refine((data) => data.rua?.trim() || data.ruaId?.trim(), {
    message: 'Rua é obrigatória',
    path: ['rua'],
  })

export const utenteEditDefaultValues: UtenteEditFormValues = {
  nome: '',
  email: '',
  numeroContribuinte: '',
  numeroUtente: '',
  observacoes: '',
  status: 0,
  aviso: '',
  desistencia: false,
  tipoConsulta: 0,
  dataNascimento: '',
  dataEmissaoCartaoIdentificacao: '',
  dataValidadeCartaoIdentificacao: '',
  sexoId: null,
  estadoCivilId: null,
  habilitacaoId: null,
  grupoSanguineoId: null,
  cronico: false,
  numeroCartaoIdentificacao: '',
  nomeMae: '',
  nomePai: '',
  naturalidade: '',
  nacionalidade: '',
  profissaoId: null,
  arquivo: '',
  ccValidado: null,
  ccDataValidacao: '',
  paisId: '',
  distritoId: '',
  concelhoId: '',
  freguesiaId: '',
  codigoPostalId: '',
  rua: '',
  ruaId: '',
  numeroPorta: '',
  andarRua: '',
  morada: '',
  indicativoTelefone: '+351',
  telefone: '',
  telemovel: '',
  numeroSegurancaSocial: '',
  condicaoSns: null,
  entidadeFinanceiraResponsavelId: null,
  numeroBeneficiarioEfr: '',
  dataValidadeEfr: '',
  migranteTipoCartao: '',
  tipoTaxaModeradora: null,
  migrante: false,
  nDocMigrante: '',
  provenienciaUtenteId: null,
  organismoId: null,
  seguradoraId: null,
  centroSaudeId: null,
  medicoExternoId: null,
  medicoId: null,
  subsistemaLinhas: [],
  empresaId: null,
  statusSelecionado: true,
}

