import { z } from 'zod'

import type { OrganismoEditFormValues } from '../organismo-edit-form-types'

export const organismoEditSchema = z
  .object({
    nome: z.string().min(1, 'Nome é obrigatório'),
    nomeComercial: z.string().optional(),
    abreviatura: z.string().optional(),
    email: z.string().min(1, 'Email é obrigatório').email('Email inválido'),
    numeroContribuinte: z.string().min(1, 'NIF é obrigatório'),
    observacoes: z.string().optional(),
    status: z.coerce.number().int().min(0).max(3),
    telefone: z.string().optional(),
    contacto: z.string().optional(),
    globalbooking: z.boolean().optional(),
    paisId: z.string().min(1, 'País é obrigatório'),
    distritoId: z.string().min(1, 'Distrito é obrigatório'),
    concelhoId: z.string().min(1, 'Concelho é obrigatório'),
    freguesiaId: z.string().min(1, 'Freguesia é obrigatória'),
    codigoPostalId: z.string().min(1, 'Código Postal é obrigatório'),
    rua: z.string().optional(),
    ruaId: z.string().optional(),
    numeroPorta: z.string().min(1, 'N.º Porta é obrigatório'),
    andarRua: z.string().min(1, 'Andar é obrigatório'),
    desconto: z.string().optional(),
    descontoUtente: z.string().optional(),
    prazoPagamento: z.string().optional(),
    entidadeNatureza: z
      .array(
        z.object({
          codigoEntidade: z.string(),
          natureza: z.string(),
        }),
      )
      .optional()
      .default([]),
  })
  .refine((data) => data.rua?.trim() || data.ruaId?.trim(), {
    message: 'Rua é obrigatória',
    path: ['rua'],
  })
  .passthrough()

export const organismoEditDefaultValues: OrganismoEditFormValues = {
  nome: '',
  nomeComercial: '',
  abreviatura: '',
  email: '',
  numeroContribuinte: '',
  observacoes: '',
  status: 1,
  telefone: '',
  fax: '',
  contacto: '',
  globalbooking: false,
  nacional: false,
  codigoClinica: '',
  localidade: '',
  paisId: '',
  distritoId: '',
  concelhoId: '',
  freguesiaId: '',
  codigoPostalId: '',
  rua: '',
  ruaId: '',
  numeroPorta: '',
  andarRua: '',
  categoria: '',
  numeroPagamentos: '',
  desconto: '',
  descontoUtente: '',
  prazoPagamento: '',
  apolice: '',
  avenca: '',
  bancoId: '',
  nib: '',
  designaTratamentos: '',
  dataInicioContrato: '',
  dataFimContrato: '',
  limitarConsultas: false,
  numeroConsultas: '',
  contabilizarFaltas: false,
  faturaCredencial: 0,
  condicaoPagamento: '',
  tipoModoPagamento: '',
  assinarPagaDocumento: false,
  admissaoCC: false,
  inactivo: false,
  discriminaServicos: false,
  apresentarCredenciaisPrimeiraSessao: 0,
  apresentarCredenciaisTipoConsulta: 0,
  contabContaFA: '',
  contabTipoContaFA: '',
  contabContaFR: '',
  contabTipoContaFR: '',
  ars: '',
  codigoRegiao: '',
  codigoULSNova: '',
  codigoFaturacao: '',
  entidadeNatureza: [],
  cServicoFaturaResumo: '',
  faturarPorDatas: false,
  trust: false,
  adm: false,
  sadgnr: false,
  sadpsp: false,
}

