import { z } from 'zod'

import type { MedicoEditFormValues } from '../types/medico-edit-form-types'

export const medicoEditSchema = z.object({
  nome: z.string().min(1, 'Nome é obrigatório'),
  email: z.string().optional(),
  numeroContribuinte: z.string().min(1, 'NIF é obrigatório'),
  observacoes: z.string().optional(),
  status: z.coerce.number().int().min(0).max(3).optional(),
  dataNascimento: z.string().optional(),
  dataEmissaoCartaoIdentificacao: z.string().optional(),
  dataValidadeCartaoIdentificacao: z.string().optional(),
  sexo: z.union([z.coerce.number().int().min(0).max(2), z.null()]).optional(),
  sexoId: z.string().nullable().optional(),
  estadoCivil: z.union([z.coerce.number().int().min(0).max(4), z.null()]).optional(),
  estadoCivilId: z.string().nullable().optional(),
  nacionalidade: z.string().optional(),
  naturalidade: z.string().optional(),
  numeroCartaoIdentificacao: z.string().optional(),
  arquivo: z.string().optional(),
  carteira: z.string().optional(),
  nomeUtilizador: z.string().optional(),
  numeroIdentificacaoBancaria: z.string().optional(),
  paisId: z.string().nullable().optional(),
  distritoId: z.string().nullable().optional(),
  concelhoId: z.string().nullable().optional(),
  freguesiaId: z.string().nullable().optional(),
  codigoPostalId: z.string().nullable().optional(),
  rua: z.string().optional(),
  ruaId: z.string().nullable().optional(),
  numeroPorta: z.string().optional(),
  andarRua: z.string().optional(),
  indicativoTelefone: z.string().optional(),
  telefone: z.string().optional(),
  telemovel: z.string().optional(),
  fax: z.string().optional(),
  director: z.boolean().optional(),
  categoriaEspecialidadeId: z.string().nullable().optional(),
  especialidadeId: z.string().nullable().optional(),
  margem: z.number().nullable().optional(),
  loginPRVR: z.string().optional(),
  comunicacaoNif: z.boolean().optional(),
  comunicacaoNifAdse: z.boolean().nullable().optional(),
  grupoFuncional: z.string().optional(),
  letra: z.string().optional(),
  cartaoCidadaoMedico: z.coerce.number().int().min(0).optional(),
  idUtilizador: z.string().nullable().optional(),
  globalbooking: z.boolean().optional(),
  urlFoto: z.string().nullable().optional(),
  urlFotoAssinatura: z.string().nullable().optional(),
})

export const medicoEditDefaultValues: MedicoEditFormValues = {
  nome: '',
  email: '',
  numeroContribuinte: '',
  observacoes: '',
  status: 0,
  dataNascimento: '',
  dataEmissaoCartaoIdentificacao: '',
  dataValidadeCartaoIdentificacao: '',
  sexo: null,
  sexoId: null,
  estadoCivil: null,
  estadoCivilId: null,
  nacionalidade: '',
  naturalidade: '',
  numeroCartaoIdentificacao: '',
  arquivo: '',
  carteira: '',
  nomeUtilizador: '',
  numeroIdentificacaoBancaria: '',
  paisId: null,
  distritoId: null,
  concelhoId: null,
  freguesiaId: null,
  codigoPostalId: null,
  rua: '',
  ruaId: null,
  numeroPorta: '',
  andarRua: '',
  indicativoTelefone: '+351',
  telefone: '',
  telemovel: '',
  fax: '',
  director: false,
  especialidadeId: null,
  margem: null,
  loginPRVR: '',
  comunicacaoNif: false,
  comunicacaoNifAdse: null,
  grupoFuncional: '',
  letra: '',
  cartaoCidadaoMedico: 0,
  idUtilizador: null,
  globalbooking: false,
  urlFoto: null,
  urlFotoAssinatura: null,
  categoriaEspecialidadeId: null,
}

